var car = "subaru";
console.log("Is car == \"subaru\"? I predict True.");
console.log(car == "subaru");
console.log("Is car == \"ford\"? I predict False.");
console.log(car == "ford");
console.log("Is car.length == 6? I predict True.");
console.log(car.length == 6);
console.log("Is car[0] == \"s\"? I predict True.");
console.log(car[0] == "s");
console.log("Is car[5] == \"u\"? I predict True.");
console.log(car[5] == "u");
console.log("Is car.toLowerCase() == \"subaru\"? I predict True.");
console.log(car.toLowerCase() == "subaru");
console.log("Is car.toUpperCase() == \"SUBARU\"? I predict True.");
console.log(car.toUpperCase() == "SUBARU");
console.log("Is car.charAt(0) == \"S\"? I predict False.");
console.log(car.charAt(0) == "S");
console.log("Is car.endsWith(\"U\")? I predict False.");
console.log(car.endsWith("U"));
console.log("Is car.startsWith(\"sub\")? I predict True.");
console.log(car.startsWith("sub"));
